// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOC0I2stNn9aiJCCAKar27CL_kvQdtRR4',
    appId: '1:681503265172:android:53e5a90e7544ca2dd03f81',
    messagingSenderId: '681503265172',
    projectId: 'notes-firebase-f2d88',
    storageBucket: 'notes-firebase-f2d88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYc56eVskfvaZRmjHzejV1m8Z7WEe8tCo',
    appId: '1:681503265172:ios:a504fd70624c2155d03f81',
    messagingSenderId: '681503265172',
    projectId: 'notes-firebase-f2d88',
    storageBucket: 'notes-firebase-f2d88.appspot.com',
    androidClientId: '681503265172-cbeucshcr0l1u3thnmi0vsivl7pbjrvc.apps.googleusercontent.com',
    iosClientId: '681503265172-q2et18t3aqhkklr3mdf2j3b4e5e1p7ke.apps.googleusercontent.com',
    iosBundleId: 'com.example.freedomChatApp',
  );
}
